import { Download, FileBarChart, Map, RefreshCw } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { api, download } from '../api'
import { MetricChart } from '../components/MetricChart'
import { EmptyState, PageHeader } from '../components/Common'
import { useJobs } from '../jobs'
import type { Bootstrap, WeeklyReport } from '../types'

export function ReportsPage() { const { data } = useQuery({ queryKey: ['bootstrap'], queryFn: () => api<Bootstrap>('/bootstrap') }); const { start, busy } = useJobs(); return <><PageHeader eyebrow="In-memory documents" title="Reports" description="Generate a seven-day health report or download the latest RENPHO composition report." actions={<button className="button button--primary" disabled={busy} onClick={() => void start('/reports/weekly', {})}><RefreshCw />Generate report</button>} /><section className="report-grid"><article className="report-card"><FileBarChart /><span className="eyebrow">Weekly health</span><h2>Training, recovery and trends</h2><p>Seven days of Garmin, RENPHO and manual data with a 30-day lifestyle context.</p>{data?.latest_weekly_report_id ? <Link className="button button--primary" to={`/reports/weekly/${data.latest_weekly_report_id}`}>Open latest report</Link> : <span className="muted">No report in memory</span>}</article><article className="report-card"><Map /><span className="eyebrow">Privacy option</span><h2>Routes are opt-in</h2><p>Location and GPS points remain in memory. Map tiles are disabled by default.</p><button className="button" disabled={busy} onClick={() => void start('/reports/weekly', { include_routes: true, map_tiles_enabled: false })}>Generate with route lines</button></article></section></> }

export function WeeklyReportPage() { const { reportId = '' } = useParams(); const { data, isLoading, error } = useQuery({ queryKey: ['weekly-report', reportId], queryFn: () => api<WeeklyReport>(`/reports/weekly/${reportId}`) }); if (isLoading) return <EmptyState title="Opening report" description="Loading the in-memory snapshot." />; if (error || !data) return <EmptyState title="Report unavailable" description="Reports live only for the current GUI process. Generate a new report." />; return <><PageHeader eyebrow={`${data.start_date} – ${data.end_date}`} title="7-day health report" description={`Generated ${new Date(data.generated_at).toLocaleString()}. Observations are not medical diagnoses.`} actions={<button className="button button--primary" onClick={() => void download(`/reports/weekly/${data.id}/download`, `weekly-health-report-${data.start_date}-to-${data.end_date}.pdf`)}><Download />Download PDF</button>} /><section className="report-summary">{Object.entries(data.summary).map(([label, value]) => <article key={label}><span>{label.replaceAll('_', ' ')}</span><strong>{value}</strong></article>)}</section><section className="chart-grid">{data.charts.charts.map((chart) => <article className="panel" key={chart.id}><div className="panel__head"><h2>{chart.title}</h2></div><MetricChart chart={chart} /></article>)}</section><section className="panel section-gap"><div className="panel__head"><h2>Insights and limitations</h2><span>{data.availability.unavailable.length} unavailable</span></div><div className="insight-list">{data.insights.map((item, index) => <article key={`${item.category}-${index}`}><span className="insight-level">{item.category}</span><p>{item.text}</p>{item.source_url && <a className="text-link" href={item.source_url} target="_blank" rel="noreferrer">{item.source_title}</a>}</article>)}</div></section></> }
